In [2]:
import pandas as pd
import numpy as np
import os
import glob

In [6]:
data_path = os.path.join(os.getcwd(), 'data','A_DeviceMotion_data')
if os.path.exists(data_path):
    print(f"데이터 경로 확인: {data_path}")
else:
    print("경로를 찾을 수 없습니다.")

데이터 경로 확인: /Users/linerenza/Desktop/비정형데이터분석/data/A_DeviceMotion_data

In [7]:
# 모든 데이터를 저장할 리스트
all_data = []

# 폴더 전체 탐색
for root, dirs, files in os.walk(data_path):
    for file in files:
        if file.endswith(".csv"):
            file_path = os.path.join(root, file)

            # CSV 읽기
            df = pd.read_csv(file_path, index_col=0)

            # 파일 이름 정보 추가
            df["source_file"] = file

            # 리스트에 저장
            all_data.append(df)

# 모든 데이터 하나로 합치기
final_df = pd.concat(all_data, ignore_index=True)

In [8]:
# 결과 확인
print("데이터 크기:", final_df.shape)
display(final_df.head())

print("데이터 통계:")
display(final_df.describe()) #기초 통계 + 이상치 알기 위해

데이터 크기: (2825730, 14)

,attitude.pitch,attitude.yaw,gravity.x,gravity.y,gravity.z,rotationRate.x,rotationRate.y,rotationRate.z,userAcceleration.x,userAcceleration.y,userAcceleration.z,source_file,mag_acc,attitude.roll
0,-1.077507,-2.261502,-0.404768,0.880780,0.245713,-1.264215,-1.027909,-0.947909,0.282683,-0.254346,-0.407670,processed_sensor_data.csv,0.557491,NaN
1,-1.049759,-2.284278,-0.417081,0.867303,0.271686,-1.162024,-0.269118,-0.848823,0.256712,0.079154,-0.560291,processed_sensor_data.csv,0.621363,NaN
2,-1.026749,-2.297008,-0.432082,0.855621,0.284961,-0.665042,0.520170,-0.726722,0.253600,0.346680,-0.463275,processed_sensor_data.csv,0.631762,NaN
3,-1.012749,-2.290595,-0.445311,0.848291,0.286507,-0.079809,0.055322,-0.604534,0.411818,0.459372,-0.510293,processed_sensor_data.csv,0.800635,NaN
4,-1.007262,-2.274149,-0.452661,0.845372,0.283600,0.456097,-0.186877,-0.441315,0.311594,0.477305,-0.925049,processed_sensor_data.csv,1.086566,NaN

데이터 통계:

,attitude.pitch,attitude.yaw,gravity.x,gravity.y,gravity.z,rotationRate.x,rotationRate.y,rotationRate.z,userAcceleration.x,userAcceleration.y,userAcceleration.z,mag_acc,attitude.roll
count,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,2.825730e+06,1.412865e+06,1.412865e+06
mean,-9.866487e-01,-1.492687e-01,4.213359e-02,7.547222e-01,-1.388248e-01,5.321167e-03,1.458119e-02,1.276031e-02,-3.910640e-03,4.424380e-02,3.927177e-02,4.253801e-01,-1.760427e-01
std,4.940859e-01,1.544769e+00,3.388300e-01,3.332649e-01,4.283231e-01,1.292916e+00,1.226470e+00,8.080410e-01,3.282089e-01,5.275662e-01,3.762120e-01,5.917344e-01,1.566652e+00
min,-1.569974e+00,-3.141588e+00,-9.998220e-01,-9.999930e-01,-9.999990e-01,-1.736579e+01,-1.841441e+01,-1.215124e+01,-6.369264e+00,-5.673592e+00,-7.743481e+00,1.177879e-04,-3.141590e+00
25%,-1.358278e+00,-1.277552e+00,-1.725300e-01,5.837930e-01,-3.922410e-01,-2.860300e-01,-1.669860e-01,-9.733300e-02,-4.751300e-02,-6.213600e-02,-2.361300e-02,2.662709e-02,-1.480050e+00
50%,-1.181032e+00,-1.356530e-01,1.991400e-02,9.249990e-01,-9.690200e-02,-3.940000e-04,3.250000e-04,1.770000e-04,8.910000e-04,4.336000e-03,3.433000e-03,1.971418e-01,1.222180e-01
75%,-6.233930e-01,8.291430e-01,2.721440e-01,9.775030e-01,8.488200e-02,1.163210e-01,2.312710e-01,1.133280e-01,4.428400e-02,5.176600e-02,1.047770e-01,6.181895e-01,8.763600e-01
max,1.567175e+00,3.141584e+00,9.999980e-01,1.000000e+00,9.813120e-01,1.046806e+01,1.754312e+01,1.143624e+01,7.120793e+00,7.322722e+00,8.125357e+00,1.011331e+01,3.141579e+00

In [9]:
def calculate_magnitude(df, x_col, y_col, z_col):
    """
    x, y, z 컬럼을 받아 벡터의 크기(Magnitude)를 계산하는 함수 #힘의 크기 알게 위해
    """

    x = df[x_col]
    y = df[y_col]
    z = df[z_col]

    # magnitude = sqrt(x^2 + y^2 + z^2)
    magnitude = np.sqrt(x**2 + y**2 + z**2)

    return magnitude

In [10]:
# 함수 적용 및 새로운 컬럼 생성
final_df['mag_acc'] = calculate_magnitude(
    final_df,
    'userAcceleration.x',
    'userAcceleration.y',
    'userAcceleration.z'
)

# 결과 확인
print(final_df[['userAcceleration.x', 'mag_acc']].head())

   userAcceleration.x   mag_acc
0            0.282683  0.557491
1            0.256712  0.621363
2            0.253600  0.631762
3            0.411818  0.800635
4            0.311594  1.086566

In [11]:
BASE_PATH = data_path

csv_path = f"{BASE_PATH}/processed_sensor_data.csv"
pkl_path = f"{BASE_PATH}/sensor_data.pkl"

final_df.to_csv(csv_path, index=False)
final_df.to_pickle(pkl_path)

print("저장 완료")

저장 완료